### ISSUE TITLE
小白，想知道最后一个js怎么用，似乎tamper monkey上用不了，那我应该用什么软件呢

### ISSUE THREAD

**Issue by Wangjn258** [ZiuChen/userscript#1]
求助求助

**Comment by Wangjn258** [comment]
由于我只会复制粘贴，对于不是用于浏览器的脚本一窍不通，希望大佬指点指点

**Comment by ZiuChen** [comment]
目前README上的最后一个是这条[uTools快捷命令合集](https://github.com/ZiuChen/userscript/blob/main/src/uToolsQuickCommands)，我不清楚你指的是不是这一条
要使用这些快捷命令脚本，你需要安装uTools并且在其中安装“快捷命令”插件。
uTools是一款十分强大的提效软件，这里是uTools的官网：https://u.tools/

**Comment by Wangjn258** [comment]
是的是的，很好的解决了我的问题，十分感谢。
